
<?php

/**
 * @file
 * Hello module.
 */
function Servicestatus_page_attachments(array &$attachments) {
 if (\Drupal::routeMatch()->getRouteName() === 'page_manager.page_view_home_page') {
   $attachments['#attached']['library'][] = 'Servicestatus/Servicestatus';
 }
}

function Servicestatus_theme($existing, $type, $theme, $path) {
  return array('Servicestatus' =>                  // this is the name of the template
           array(
            'variables' => array(
                'title' => 'Default title',
                'description' => null,
             ),

        )
    );
}