
<?php

/**
 * @file
 * Hello module.
 */
function Servicestatus_page_attachments(array &$attachments) {
  if (!\Drupal::currentUser()->hasPermission('access Cloudfare')) {
    return;
  }

  $attachments['#attached']['library'][] = 'Servicestatus/Servicestatus';
}

function Servicestatus_theme($existing, $type, $theme, $path) {
  return array('Servicestatus' =>                  // this is the name of the template
           array(
            'variables' => array(
                'title' => 'Default title',
                'description' => null,
             ),

        )
    );
}