
<?php

/**
 * @file
 * Hello module.
 */
function tripplanner_page_attachments(array &$attachments) {
 if (\Drupal::routeMatch()->getRouteName() === 'page_manager.page_view_home_page' || \Drupal::routeMatch()->getRouteName() === 'page_manager.page_view_nyct' || \Drupal::routeMatch()->getRouteName() === 'page_manager.page_view_lirr' || \Drupal::routeMatch()->getRouteName() === 'page_manager.page_view_mnr' || \Drupal::routeMatch()->getRouteName() === 'page_manager.page_view_bandt') {
    $attachments['#attached']['library'][] = 'tripplanner/Tripplanner';
  }
}
function tripplanner_theme() {
  return [
    'tripplanner' => [
      // Here you can pass any variables you want, if necessary.
      'variables' => ['trip1' => NULL],
       'template' => 'tripplanner'
    ],
  ];
}